version: '3.8'

services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile.dev
    volumes:
      - ./back-end:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./back-end/.env
    command: npm run dev
    depends_on:
      - db

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile.dev
    volumes:
      - ./front-end:/app
      - /app/node_modules
    working_dir: /app
    ports:
      - "5173:5173"
    command: npm run dev
    depends_on:
      - backend

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cash-flow-db-1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
