version: "3"
services:
  postgres-db:
    image: bitnami/postgresql:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: database
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  mongo-db:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
